### ISSUE TITLE
Wrong automatic scrolling

### ISSUE THREAD

**Issue by rliebscher** [607011/chilly#1]
When you are on the lower half of the board and move upwards, the view scrolls all the time so that santa is on the last visible line. (even if Santa would not move out of the view) So you always have to scroll manually again to see the lower part of the board.
Probably something wrong in scrollIntoView(). It would be enough to scroll so far that Santa is at one of the border of the view in case he letft it.

**Comment by 607011** [comment]
We've experienced this issue with Safari.  That's why the [article](https://www.heise.de/select/ct/2023/28/2329707360694897070) states that the game is successfully tested with Firefox and Chrome. Which browser on which platform do you use, @rliebscher ?

**Comment by 607011** [comment]
Ahaaa! I've checked the (incomplete) move sequence you sent in. Now I see what you mean, @rliebscher

**Comment by rliebscher** [comment]
Firefox 119.0.1
